export const BOARD_SIZE = 15;
export const CENTER = 7;

export const LETTER_SCORES = {
  A:1,B:3,C:3,D:2,E:1,F:4,G:2,H:4,I:1,J:8,K:5,L:1,M:3,
  N:1,O:1,P:3,Q:10,R:1,S:1,T:1,U:1,V:4,W:4,X:8,Y:4,Z:10
};

export const CONSONANT_BAG = 'BBCCCDDDDFFGGGHHHJKLLLLMMMNNNNNNNNPPQRRRRRRRSSSSSSTTTTTTTTTVVWWXYYZ'.split('');
export const VOWEL_BAG     = 'AAAAAAAAAAAEEEEEEEEEEEEEEIIIIIIIIIIOOOOOOOOOOOUUUUU'.split('');

export const TW = 'TW', DW = 'DW', TL = 'TL', DL = 'DL', ST = 'ST', EM = '';

// Standard Scrabble premium square layout
export const PREMIUM = [
  [TW,EM,EM,DL,EM,EM,EM,TW,EM,EM,EM,DL,EM,EM,TW],
  [EM,DW,EM,EM,EM,TL,EM,EM,EM,TL,EM,EM,EM,DW,EM],
  [EM,EM,DW,EM,EM,EM,DL,EM,DL,EM,EM,EM,DW,EM,EM],
  [DL,EM,EM,DW,EM,EM,EM,DL,EM,EM,EM,DW,EM,EM,DL],
  [EM,EM,EM,EM,DW,EM,EM,EM,EM,EM,DW,EM,EM,EM,EM],
  [EM,TL,EM,EM,EM,TL,EM,EM,EM,TL,EM,EM,EM,TL,EM],
  [EM,EM,DL,EM,EM,EM,DL,EM,DL,EM,EM,EM,DL,EM,EM],
  [TW,EM,EM,DL,EM,EM,EM,ST,EM,EM,EM,DL,EM,EM,TW],
  [EM,EM,DL,EM,EM,EM,DL,EM,DL,EM,EM,EM,DL,EM,EM],
  [EM,TL,EM,EM,EM,TL,EM,EM,EM,TL,EM,EM,EM,TL,EM],
  [EM,EM,EM,EM,DW,EM,EM,EM,EM,EM,DW,EM,EM,EM,EM],
  [DL,EM,EM,DW,EM,EM,EM,DL,EM,EM,EM,DW,EM,EM,DL],
  [EM,EM,DW,EM,EM,EM,DL,EM,DL,EM,EM,EM,DW,EM,EM],
  [EM,DW,EM,EM,EM,TL,EM,EM,EM,TL,EM,EM,EM,DW,EM],
  [TW,EM,EM,DL,EM,EM,EM,TW,EM,EM,EM,DL,EM,EM,TW],
];

export const PREMIUM_LABELS = { TW: 'TW', DW: 'DW', TL: 'TL', DL: 'DL', ST: '★', '': '' };
